import { Prisma, NotificationType, Media } from "@prisma/client";

export function getUserDataSelect(loggedInUserId?: string | null) {
  const select = {
    id: true,
    username: true,
    displayName: true,
    avatarUrl: true,
    bio: true,
    createdAt: true,
    email: true,
    passwordHash: true,
    deletedAt: true, // Include deletedAt field
    isDatingActive: true,
    userDatingProfile: {
      select: {
        id: true,
        age: true,
        height: true,
        gender: true,
        sexualOrientation: true,
        coronavirusVaccinated: true,
        religion: true,
        zipCode: true,
        city: true,
      },
    },
    userPreferences: {
      select: {
        calendar: true,
      },
    },
    userDatingPreferences: {
      select: {
        id: true,
        preferredGender: true,
        preferredSexualOrientation: true,
        preferredMinAge: true,
        preferredMaxAge: true,
        preferredMaxDistanceKm: true,
        preferredMinHeight: true,
        preferredMaxHeight: true,
        preferredCoronavirusVaccinated: true,
        preferredReligions: true,
      },
    },

    userInstruments: {
      select: {
        instrument: {
          select: {
            id: true,
            name: true,
          },
        },
      },
    },
    userSkills: {
      select: {
        skill: {
          select: {
            id: true,
            name: true,
          },
        },
      },
    },
    _count: {
      select: {
        posts: true,
        followers: true,
      },
    },
  } satisfies Prisma.UserSelect;

  // `followers` answers "am *I* following this user?". It used to be attached
  // only when loggedInUserId was set, which made the return type a union and
  // left `user.followers` undefined for anonymous viewers — while
  // UserWithFollowerStatus declares it required and Post.tsx reads
  // `post.user.followers` directly. Selecting with a filter that matches no
  // rows keeps the shape constant and the inferred type a single object.
  return {
    ...select,
    followers: {
      where: loggedInUserId
        ? { followerId: loggedInUserId }
        : { followerId: { in: [] as string[] } },
      select: { followerId: true },
    },
  } satisfies Prisma.UserSelect;
}

export type UserData = Prisma.UserGetPayload<{
  select: ReturnType<typeof getUserDataSelect>;
}>;

export function getEventDataInclude(loggedInUserId: string) {
  return {
    createdBy: {
      select: getUserDataSelect(loggedInUserId),
    },
    attendees: {
      select: {
        user: {
          select: getUserDataSelect(loggedInUserId),
        },
      },
    },
    helpWantedSkills: {
      select: {
        skill: {
          select: {
            id: true,
            name: true,
          },
        },
      },
    },
    _count: {
      select: {
        attendees: true,
      },
    },
  } satisfies Prisma.EventInclude;
}

export type EventData = Prisma.EventGetPayload<{
  include: ReturnType<typeof getEventDataInclude>;
}>;

export function getPostDataInclude(loggedInUserId?: string | null) {
  // Viewer-specific relations answer "did *I* like/dislike/bookmark this?".
  //
  // These used to be omitted entirely for an anonymous viewer, which made
  // `likes`/`dislikes`/`bookmarks` undefined at runtime while PostData declared
  // them required — and Post.tsx calls `post.likes.some(...)` with no guard.
  // The `as unknown as PostData[]` casts in the routes were what let that
  // mismatch compile. Selecting with a filter that matches no rows keeps the
  // shape constant (empty arrays for anonymous viewers) and keeps the inferred
  // type a single object rather than a union.
  const viewerFilter = loggedInUserId
    ? { userId: loggedInUserId }
    : { userId: { in: [] as string[] } };

  const viewerRelations = {
    likes: { where: viewerFilter, select: { userId: true } },
    dislikes: { where: viewerFilter, select: { userId: true } },
    bookmarks: { where: viewerFilter, select: { userId: true } },
  };

  const countSelect = {
    select: {
      likes: true,
      dislikes: true,
      comments: { where: { parentId: null } },
    },
  };

  // A shared post can itself be a share, so this nests one level. It is written
  // out rather than generated by a recursive helper: the old helper was typed
  // `(depth: number): any`, and that `any` is what stopped Prisma from
  // inferring the payload and forced PostData to be maintained by hand.
  const sharedPostSelect = {
    id: true,
    content: true,
    createdAt: true,
    user: { select: getUserDataSelect(loggedInUserId) },
    attachments: true,
    sharedCount: true,
    _count: countSelect,
    ...viewerRelations,
  };

  return {
    user: { select: getUserDataSelect(loggedInUserId) },
    attachments: true,
    sharedFrom: {
      select: {
        ...sharedPostSelect,
        sharedFrom: { select: sharedPostSelect },
      },
    },
    _count: countSelect,
    Group: { select: { id: true, name: true } },
    ...viewerRelations,
  } satisfies Prisma.PostInclude;
}

// UserData is derived from getUserDataSelect, so it already *is* this shape.
// This was a separate ~40-line hand-written mirror of the same select, and it
// had drifted: it declared preferredGender/preferredSexualOrientation as
// `string` when the schema makes them nullable.
export type UserWithFollowerStatus = UserData;

export interface NotificationData {
  id: string;
  recipientId: string;
  issuerId: string;
  postId: string | null;
  type: NotificationType; // Correctly imported type
  read: boolean;
  eventId: string | null;
  matchId: string | null; // Link to match for MATCH type notifications
  createdAt: Date;

  issuer: UserWithFollowerStatus;
  post: {
    id: string;
    content: string;
  } | null;
  event: {
    id: string;
    title: string;
    location: string;
  } | null;
}

export interface NotificationsPage {
  notifications: NotificationData[];
  nextCursor: string | null;
}

export interface FollowerInfo {
  followers: number;
  isFollowedByUser: boolean;
}

export interface LikeInfo {
  likes: number;
  isLikedByUser: boolean;
}

export interface DislikeInfo {
  dislikes: number;
  isDislikedByUser: boolean;
}

export interface BookmarkInfo {
  isBookmarkedByUser: boolean;
}

export interface NotificationCountInfo {
  unreadCount: number;
}

export interface MessageCountInfo {
  unreadCount: number;
}

export interface Event {
  id: string;
  title: string;
  location: string;
  when: Date;
  startTime: string;
  endTime: string;
  performers: string[];
  description: string;
  url: string;
  createdById: string;
  isCancelled: boolean;
  status: string;
  createdAt: string;
  updatedAt: string;
  visibility: string;
}

export interface EventsPage {
  events: EventData[];
  nextCursor: string | null;
}

export interface CalendarProps {
  events: Event[];
  currentDate: Date;
}

export interface CalendarDayProps {
  day: Date;
  events: Event[];
  onClick: (day: Date, events: Event[]) => void;
}

export interface PageProps {
  searchParams: {
    q?: string;
  };
}

export interface CalendarGridProps {
  currentDate: Date;
  events: Event[];
  onSelectDay: (day: Date, events: Event[]) => void;
}

export interface ConfirmDeletionModalProps {
  isOpen: boolean;
  onConfirm: () => void;
  onCancel: () => void;
  title: string;
  message: string;
}

export interface EditState {
  title: string;
  startTime: string;
  endTime: string;
  isEditing: boolean;
  editedTitle: string;
  editedStartTime: string;
  editedEndTime: string;
}

// Helper type to get the payload structure from getPostDataInclude
// Ensures we include likes, dislikes, bookmarks conditionally
type PostPayloadCreator<T extends string | null | undefined> =
  Prisma.PostGetPayload<{ include: ReturnType<typeof getPostDataInclude> }>;

// Manually define PostData to ensure the user field has the correct type
// Derived from the include, matching how UserData and EventData are defined.
// This was previously ~50 hand-maintained lines that had to mirror
// getPostDataInclude by eye — the mismatch it accumulated is why every route
// needed `as unknown as PostData[]` to compile.
export type PostData = Prisma.PostGetPayload<{
  include: ReturnType<typeof getPostDataInclude>;
}>;

export interface PostsPage {
  posts: PostData[];
  nextCursor: string | null;
}

export function getGroupMemberSelect() {
  return {
    userId: true,
    groupId: true,
    role: true,
    joinedAt: true,
    group: {
      select: {
        id: true,
        name: true,
        description: true,
        ownerId: true,
      },
    },
    user: {
      select: {
        id: true,
        username: true,
        displayName: true,
      },
    },
    acceptedInvite: true,
  } satisfies Prisma.GroupMemberSelect;
}

export type GroupMembershipData = Prisma.GroupMemberGetPayload<{
  include: ReturnType<typeof getGroupMemberSelect>;
}>;

export function getCommentDataInclude(loggedInUserId?: string | null) {
  return {
    user: {
      select: getUserDataSelect(loggedInUserId),
    },
    parent: {
      select: {
        id: true,
        content: true,
        user: {
          select: {
            id: true,
            username: true,
            displayName: true,
          },
        },
      },
    },
    replies: {
      include: {
        user: {
          select: getUserDataSelect(loggedInUserId),
        },
        replies: {
          include: {
            user: {
              select: getUserDataSelect(loggedInUserId),
            },
          },
        },
      },
    },
    likes: loggedInUserId
      ? {
          where: {
            userId: loggedInUserId,
          },
          select: {
            isLike: true,
          },
        }
      : false,
    _count: {
      select: {
        replies: true,
        likes: {
          where: {
            isLike: true,
          },
        },
      },
    },
  } satisfies Prisma.CommentInclude;
}

export type CommentData = Prisma.CommentGetPayload<{
  include: ReturnType<typeof getCommentDataInclude>;
}>;

export interface CommentsPage {
  comments: CommentData[];
  previousCursor: string | null;
}
