// Sample Configuration File: Adjust values below to match your project's setup

module.exports = {
  // Uncomment the relevant teams or add your own in the Describe block or It block:
  //  describe('[oregano] Unit test our math functions', () => {
  //    context('math', () => {
  //      it('can add numbers [C2452][smoke]', () => {
  teamNames: [
    "AuthTeam",
    "SocialTeam",
    "EventsTeam",
    "GroupsTeam",
    "MessagingTeam",
    "NotificationsTeam",
    "MediaTeam",
    "PlatformTeam",
  ],
  // (default list) Uncomment the relevant test types or add your own by modifying your folder structure [framework]/ui/1-getting-started/todo.cy.js:
  testTypes: [
    "api",
    "ui",
    "unit",
    "integration",
    "endToEnd",
    "performance",
    "security",
    "database",
    "accessibility",
    "mobile",
  ],
  // (default list) Uncomment the relevant test categories or add your own in the Describe block or It block:
  //  describe('[oregano] Unit test our math functions', () => {
  //    context('math', () => {
  //      it('can add numbers [C2452][smoke]', () => {
  testCategories: [
    "smoke",
    "regression",
    "sanity",
    "exploratory",
    "functional",
    "load",
    "stress",
    "usability",
    "compatibility",
    "alpha",
    "beta",
  ],
  // Google Spreadsheet URL: Replace with either the actual spreadsheet ID or an environment variable.
  googleSpreadsheetId:
    "https://docs.google.com/spreadsheets/d/1oQ2Zm2kagt-MnxF7Dn98q8FbPb6gxcQJRYlzx9kx67U/edit?gid=0#gid=0",
  // Path to Google credentials file (service account JSON file): Replace with the file path or use an environment variable.
  googleKeyFilePath: "./googleCredentials.json",

  // Path to test data results file in the format generated by your test runner. Replace with the path or use an environment variable.
  testData: "./cypress/results/output.json",

  // Directory for saving CSV downloads (optional). Uncomment and replace with your preferred path or use an environment variable.
  csvDownloadsPath: "./cypress/downloads",

  weeklySummaryStartDay: "Monday",
};
